# Generated by Django 5.2.1 on 2025-05-22 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia_anios', models.IntegerField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
